### ISSUE TITLE
Please add support for Node v16.0.0

### ISSUE THREAD

**Issue by eric14142004** [zinen/node-red-contrib-dirigera#5]
Currently unable to install the palette in Node-Red docker container, as it is built with Node v16.0.0
<img width="941" alt="image" src="https://github.com/zinen/node-red-contrib-dirigera/assets/17056249/c65324c0-c623-41d9-8d96-1fa3263a4308">

**Comment by zinen** [comment]
I'll test this later. This module might already work with node v16 I just haven't tested it.

**Comment by zinen** [comment]
Try now. Install version 1.0.5

**Comment by eric14142004** [comment]
it works now, thank you for the update!
