### ISSUE TITLE
How to control just a single device like a light

### ISSUE THREAD

**Issue by jeroenboere** [zinen/node-red-contrib-dirigera#6]
Hi,

is there more information/instruction available how to control a light (for example) that is part of a group/room.
Controlling all lights in a group is working perfectly btw.

**Comment by zinen** [comment]
This would require a new feature to be implemented. It's not currently possible

**Comment by ukmoose** [comment]
As a workaround you can use scenes with specific items and use the node to control the scene.

**Comment by zinen** [comment]
Fixed in version 1.1.0 

![image](https://github.com/zinen/node-red-contrib-dirigera/assets/9595798/aa68d75a-951d-4829-95e2-264f4416c914)
