### ISSUE TITLE
Node _Name_ not used anymore

### ISSUE THREAD

**Issue by xtvdata** [zinen/node-red-contrib-dirigera#8]
The _Name_ of the nodes is not used anymore (I just upgraded from 1.0.2 - where it was working as expected).

Even entering a node name, in the flow the node still just show "dirigera".

Not an high priority, but this makes managing the flows much harder.

**Comment by zinen** [comment]
Will look into it

**Comment by zinen** [comment]
Fixed in version 1.0.7
