### ISSUE TITLE
Missing battery percentage on new remotes (after last update)

### ISSUE THREAD

**Issue by xtvdata** [zinen/node-red-contrib-dirigera#9]
Hello,
I've just realized that from mid December, for the most recent light remotes, the battery level is fixed to `-1`(object path `payload[0].attributes.batteryPercentage`).
Before that the remote was reporting a battery level that was more or less as expected.

This happens only for the most recent remotes I have (Styrbar - the square shaped ones, the older round ones still work correctly).

Here is an extract to identify the model:
```json
[{
    "type": "controller",
    "deviceType": "lightController",
    "attributes": {
        "model": "Remote Control N2",
        "manufacturer": "IKEA of Sweden",
        "firmwareVersion": "2.4.5",
        "hardwareVersion": "1",
        "productCode": "E2001",
        "batteryPercentage": -1,
    }
}]
```

**Comment by xtvdata** [comment]
Sorry, I was to quick in opening the issue.

I've double checked and it seems it's bug in Dirigera as the gateway itself reports "battery status: unknown".

I'll try to find a solution there, so please ignore this issue.

Thanks.

**Comment by zinen** [comment]
This node should directly report back what dirigera tells. So what was reported back to node-red? Either -1 or some sort of error thrown?

**Comment by xtvdata** [comment]
It reports `-1`, no errors.

However, I had a spare remote and I registered it in the gateway, yet also this one reports `-1` in the module, and `unknown` in the Ikea application as battery level.
Therefore, unfortunately I think it's a bug in Dirigera gateway itself, or in the latest firmware on the Styrbar remote controller... :-(
